### ISSUE TITLE
Service does not work at start up

### ISSUE THREAD

**Issue by jperraud** [Ckath/mergeinputs#2]
Firstly, thanks a lot for sharing this script, it was very helpful! I set up the service but realized that it did not work for me. I think the keyboards were not recognized yet - when manually restarting the service it worked. I added a `ExecStartPre=/bin/sleep 30` which resolved the problem for me. I assume there would be a smoother solution but I wasn't sure for which service one would have to wait before starting the `mergeinputs.services`.

**Comment by Ckath** [comment]
interesting, it never failed to bind to everything for me. I did notice that the service didn tinclude the
```
After=multi-user.target
```
which I normally include in most services. and should delay it till after a login is reached, at which point keyboards should have already shown up.

I'll throw that in and see if that helps the situation. otherwise just put in the pre start sleep time

**Comment by Ckath** [comment]
possibly have to go after `graphical.target`, if that also doesnt work the delay will be the way to go

**Comment by jperraud** [comment]
`After=multi-user.target`

Perfect, this solved it for me. Thanks a lot!
