### ISSUE TITLE
Using 200% CPU during use even when not typing

### ISSUE THREAD

**Issue by tjltjl** [Ckath/mergeinputs#4]
Ubuntu 22.04 (works otherwise for me on the r-go split ergonomic keyboard)

Any tips on debugging?

Also sometimes stops doing its job and I have to manually restart it (possibly when the USB is disconnected)

**Comment by Ckath** [comment]
it cant handle usb disconnects as it just opens all the devices once, it might crash or just lose that device from its merged input as it gets another uinput device of its own and gets handled as separate keyboard again.
the 200% cpu usage is probably also related to this as it pretty much becomes undefined behaviour when the device it has open suddenly disappears, not really handled as a case as it is now.

since keyboards get a new input device when reconnected theres no nice way to fix this either currently other than hoping mergeinput does crash and just letting it run in a loop or the job with autorestart. 
I could possibly add something that just solves the actual case of "yes I want to merge all keyboard input devices" which can then automagically try to deal with them disconnecting and reconnecting, looking for the new handles they get etc.

**Comment by tjltjl** [comment]
The 200% CPU usage is also when I restart it so I don't think it is caused by the disconnects...

**Comment by tjltjl** [comment]
Oops, my bad, apparently it was a previous leftover process. Now working well.

**Comment by Ckath** [comment]
phew that almost required effort on my part

**Comment by fakrep** [comment]
> Ubuntu 22.04 (works otherwise for me on the r-go split ergonomic keyboard)
> 
> Any tips on debugging?
> 
> Also sometimes stops doing its job and I have to manually restart it (possibly when the USB is disconnected)

Which exact Kernel do you have installed?
