### ISSUE TITLE
Handle new devices dynamically?

### ISSUE THREAD

**Issue by prescientmoon** [Ckath/mergeinputs#7]
Does this project handle new devices being connected after the script started running? Thinking of using it for my setup, but that's a pretty big requirement for me.

**Comment by Ckath** [comment]
it doesnt, it just grabs all devices currently present as it stands. the program itself merely combines what devices you give it, and the script just matches all device pointers and passes it to that.
workarounds would exist where you rerun it from a dbus rule on seeing a device being removed/added. due to it all being a bit taped together and the program in the end really doing near nothing complex besides merging what you pass it I've abandoned making it more featured.

could give it another look though, question has come up multiple times. and it could still keep its old working without any special flags

**Comment by filyp** [comment]
that would be great! it's also pretty critical for me

**Comment by mreiger** [comment]
Since Ubuntu 23.04 I had a problem with my r-go split keyboard and your little program saved my day!

I found a way that works for me to handle hotplugging by using a systemd path unit to wath the device directory for changes, and restart the mergeinputs service when necessary.

It is a bit ugly because it restarts the service a bunch of times when hotplugging but that does not seem to have any ill effects.

PR: https://github.com/Ckath/mergeinputs/pull/9
